### ISSUE TITLE
When entering customizable water or land size doesn't enter upon numpad enter button push

### ISSUE THREAD

**Issue by lshearer20** [HannahNBogen/OpenRCT2#10]
**OS:** [Windows 10]
**Version:** [v0.2.3]

If the user is entering in their custom land or water size and they hit enter on the main keyboard it will register their entry, but if they hit enter with the numpad enter key, it doesn't work.

**Steps to reproduce:**
1. Create a park and choose the size of the land or water you want.
2. Hit enter via the numpad enter key and notice nothing happens.

**Screenshots / Video:**

Video demonstrating the issue:
https://photos.app.goo.gl/cmMTyRdsr75xig4X6

**Comment by lshearer20** [comment]
Water and Land size entry now accepts numpad enter key.
Video showing completion:
https://photos.app.goo.gl/g11WAqmkXdKu8koL9
Via commit:
cc7d93835bbf9abd25a6260b1920ddd97663bb81

**Comment by lshearer20** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [When entering customizable water or land size doesn't enter upon numpad enter button push](https://trello.com/c/KvO3yxiL/18-when-entering-customizable-water-or-land-size-doesnt-enter-upon-numpad-enter-button-push)

**Comment by HannahNBogen** [comment]
Nice video, it helps! I actually don't have a numpad on my laptop so I cannot test this one

**Comment by lshearer20** [comment]
@kathyfreund Do you have a numpad section on your keyboard that you could verify this working?
