### ISSUE TITLE
Gates can have a double open animation

### ISSUE THREAD

**Issue by lshearer20** [HannahNBogen/OpenRCT2#11]
**OS:** [e.g. Windows 10]
**Version:** [v0.2.3]

Gates can have the animation of being opened, even if it is already open, so there must not be a check to make sure the gate is already opened when trying to open the gate.

**Steps to reproduce:**
1. Run a working park and observe a gate or door have the animation of being opened when already open.

**Screenshots / Video:**

Video of malfunctioning gates.
https://photos.app.goo.gl/R2Su1xjCJPRVXxaH8

**Comment by lshearer20** [comment]
Gates are now functioning normally.
https://photos.app.goo.gl/VynHyWH2Wcodhx9b7
via:
49ddb924e4f51328d4632da827095aed193774df

**Comment by lshearer20** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [When entering customizable water or land size doesn't enter upon numpad enter button push](https://trello.com/c/KvO3yxiL/18-when-entering-customizable-water-or-land-size-doesnt-enter-upon-numpad-enter-button-push)

**Comment by lshearer20** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gates can have a double open animation](https://trello.com/c/WPSKeJHr/20-gates-can-have-a-double-open-animation)

**Comment by HannahNBogen** [comment]
Which gates are you talking about?
The metal ones?

**Comment by lshearer20** [comment]
If you look at the video it shows exactly the ones I'm referring to. They are on the "Old Timers" "Car Ride" gates/ Car doors.

**Comment by lshearer20** [comment]
Actually based on searching for the exact animation related to those gates, "vehicle_play_scenery_door_open_sound(vehicle, tileElement)", it seems this is the only place these gates exist.

**Comment by HannahNBogen** [comment]
Thank you, I see what you mean. It looks like it's working for me. @kathyfreund does it work for you?

**Comment by kathyfreund** [comment]
I can check, do you have an .sv6 file I can plug in?

**Comment by kathyfreund** [comment]
Nevermind, I put in like 3 doors near a park entrance, and immediately one of them freaked out. Nice video btw

**Comment by lshearer20** [comment]
Here is a file that shows the gates. Just remove the ".txt" part and it should work.
[gate test.sv6.txt](https://github.com/HannahNBogen/OpenRCT2/files/3777377/gate.test.sv6.txt)
