### ISSUE TITLE
Black tiles break when loading

### ISSUE THREAD

**Issue by kathyfreund** [HannahNBogen/OpenRCT2#15]
**Steps to reproduce:**
1. Load saved game where labyrinths were used as black tiles
2. tiles should look disproportionate or look weird overall

**Comment by kathyfreund** [comment]
reverted to old working commit and added minor changes: moved RIDE_TYPE_MAZE check outside initial RIDE_TYPE_MULTI_DIMENSION_ROLLER_COASTER. get_ride(dst2->GetRideIndex()) always returned a null pointer so changed that over to check ride type instead. dca8b57

**Comment by HannahNBogen** [comment]
Which ones are the black tiles?

**Comment by HannahNBogen** [comment]
Oh nevermind, I see

**Comment by kathyfreund** [comment]
Essentially placeholders

**Comment by kathyfreund** [comment]
[example.zip](https://github.com/HannahNBogen/OpenRCT2/files/3777243/example.zip)
Here's an example if you wanna play around with it in your branch though

**Comment by HannahNBogen** [comment]
Cool, thanks. It worked for me
