### ISSUE TITLE
Park entrances limit can be overshot in editor

### ISSUE THREAD

**Issue by kathyfreund** [HannahNBogen/OpenRCT2#16]
In normal sandbox gameplay, new placed entrances would disappear after placing more than 8. By zooming in/out to the point where these entrances "disappear" from view, can continue to place more, surpassing the initial limit of 8.

funny enough discovered this issue by trying to recreate the Disneyland ticket entrance 

**Steps to reproduce:**
1. in sandbox, put several entrances
2. shrink gameplay area so that entrances minimize enough to the point where they disappear from view
3. zoom in again and place new entry points (should be able to place more that the in-game limit of 8)

**Comment by kathyfreund** [comment]
crazy experiment, but decided to keep going past 16 (after the first zoom in/out). Seems like entrance count resets after each zoom in/out? In theory, could have unlimited amount of entrances. Have not tested whether this loads back in successfully or causes eventual game crash.

**Comment by kathyfreund** [comment]
8236912

**Comment by HannahNBogen** [comment]
I tested this one this morning. I didn't see any problems. @lshearer20

**Comment by lshearer20** [comment]
I didn't replicate the initial issue, but after implementing your code it wouldn't let me make more entrances, so it seems you fixed the original bug.
