### ISSUE TITLE
Game crashes when trying to find a mechanic

### ISSUE THREAD

**Issue by HannahNBogen** [HannahNBogen/OpenRCT2#4]
Windows 10

When looking for the closest mechanic, the game will crash.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Comment by HannahNBogen** [comment]
Fixed issue - 9e8595a9bb09e5452d183d9e889a254430d2b3a8

**Comment by HannahNBogen** [comment]
Fixed issue - 9e8595a9bb09e5452d183d9e889a254430d2b3a8

**Comment by HannahNBogen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Game crashes when trying to find a mechanic](https://trello.com/c/90Nb4iEI/17-game-crashes-when-trying-to-find-a-mechanic)

**Comment by lshearer20** [comment]
implemented your code and asked for the nearest mechanic with no issues so unless there are other steps to this bug then it seems to be working now?
