### ISSUE TITLE
Roller Coaster going backwards

### ISSUE THREAD

**Issue by HannahNBogen** [HannahNBogen/OpenRCT2#5]
Windows 10

Roller coaster breaks are causing the ride to go backwards. Occurred after changing to release mode but not sure if this was the reason (it probably was not).

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

=

**Comment by HannahNBogen** [comment]
Fixed -

**Comment by HannahNBogen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Roller Coaster going backwards](https://trello.com/c/VLLIpxUQ/14-roller-coaster-going-backwards)

**Comment by HannahNBogen** [comment]
Fixed - 1eb80354d4000363820f3af67e5e00373eacd032

**Comment by lshearer20** [comment]
@HannahNBogen Do you have a file with a roller coaster that you could upload that shows this bug?
