### ISSUE TITLE
Multiple track circuits don't always work and cause bug

### ISSUE THREAD

**Issue by HannahNBogen** [HannahNBogen/OpenRCT2#6]
Windows 10

Multiple circuits is not supported and when trying to switch from using multiple circuits to using one circuit, I didn't think the switch was occurring, causing a bug.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Comment by HannahNBogen** [comment]
Issue is fixed - 
6be603cafbf0dd9a3c030e5f0b0eb1e48064fea3

**Comment by HannahNBogen** [comment]
Issue not quite fixed

**Comment by HannahNBogen** [comment]
Issue is fixed - df3b3046f6f58d516d48155da6f8a7d70cfbd119

**Comment by HannahNBogen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Multiple circuits not supported and causes bug](https://trello.com/c/NzkJj9Ok/16-multiple-circuits-not-supported-and-causes-bug)

**Comment by HannahNBogen** [comment]
Fixed - 073715fc7b4a299131aa10d66278b5249dbca58d

**Comment by HannahNBogen** [comment]
I tested this one again and the problem is still occurring. @lshearer20 @kathyfreund can you see?

**Comment by kathyfreund** [comment]
Is this the one you were showing us yesterday?

**Comment by HannahNBogen** [comment]
Yes

**Comment by kathyfreund** [comment]
Wouldn't hurt to put an else in there in the case that CanHaveMultipleCircuits, that way you can call the setter again? I'm not too sure how you determine the number of circuits or if it's even a smart idea to redefine them within this check

**Comment by kathyfreund** [comment]
I just tried it and it seems to be working for me?

**Comment by HannahNBogen** [comment]
I'm dumb I was looking at a track that has multiple circuits, it is working, phew! Thanks anyway
