### ISSUE TITLE
Complaining about running out of money with "No Money Cheat"

### ISSUE THREAD

**Issue by kathyfreund** [HannahNBogen/OpenRCT2#7]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.2.3]
**Commit/Build:** [e.g. 426e106]

When "No Money Cheat" is on, park customers complain about not having enough money.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Launch game with "No Money Cheat" enabled
2. Play [sometimes takes a while for customers to start complaining]

**Comment by kathyfreund** [comment]
fixed (1d08267), added extra flag check when price, ridePrice, or cash_in_pocket checks are made

**Comment by HannahNBogen** [comment]
I tested the code and it worked for me

**Comment by lshearer20** [comment]
@kathyfreund how do I turn on the "no money cheat"?
