### ISSUE TITLE
Maze breaks

### ISSUE THREAD

**Issue by kathyfreund** [HannahNBogen/OpenRCT2#8]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.2.3]
**Commit/Build:** [e.g. 426e106]

Opening saved game in which mazes were used affects how they were loaded

**Steps to reproduce:**
1. Open saved game where mazes were used as black tiles

**Comment by kathyfreund** [comment]
get_ride returns null - SetMazeEntry never called. Is this why it's broken?

**Comment by kathyfreund** [comment]
narrowed down to inside S6imported - class used to import saved games (*.sv6)

**Comment by lshearer20** [comment]
Could you possibly upload a *.sv6 file of the park you are looking at this issue in? Might be able to help look into the issue but would help me out if I could see exactly the park you are looking at. If you go into where your games are saved you should be able to find the park with the name you are looking into this issue at.

**Comment by lshearer20** [comment]
Or if its simple just describe the set up? not familiar with the "maze" aspects.

**Comment by kathyfreund** [comment]
You can basically make your own uses the hedges, here are some picture that I found online along with a wiki: https://rct.fandom.com/wiki/Maze
Also, github won't let me upload the .sv6 file that was attached to the original ticket

**Comment by kathyfreund** [comment]
found another way around it, attached it the example file 
[example.zip](https://github.com/HannahNBogen/OpenRCT2/files/3775275/example.zip)

**Comment by kathyfreund** [comment]
ended up reverting to an old commit that worked with some minor tweaks dca8b57
